/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_sdu_nativecode_TestNativeCode */

#ifndef _Included_com_sdu_nativecode_TestNativeCode
#define _Included_com_sdu_nativecode_TestNativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sdu_nativecode_TestNativeCode
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sdu_nativecode_TestNativeCode_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
